---
name: App-Physics-ParticleMotion
version: 1.00
author:
  - Steffen Mueller <modules at steffen-mueller dot net>
abstract: Simulations from Differential Equations
license: perl
requires:
  Config::Tiny: 0
  Math::Project3D: 0
  Math::RungeKutta: 0
  Math::Symbolic: 0.163
  Time::HiRes: 0
  Tk: 0
  Tk::Cloth: 0
recommends:
  Test::Pod: 1.0
  Test::Pod::Coverage: 1.0
build_requires:
  Test::More: 0
provides:
  App::Physics::ParticleMotion:
    file: lib/App/Physics/ParticleMotion.pm
    version: 1.00
generated_by: Module::Build version 0.2611
